# Generated by Django 3.2.5 on 2021-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.TextField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
