# Generated by Django 3.2.5 on 2021-08-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulations',
            name='coupon',
            field=models.TextField(default=b'YQ4eLCNfOwk='),
        ),
    ]
