# Generated by Django 3.2.5 on 2021-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0002_postulations_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulations',
            name='coupon',
            field=models.TextField(default=b'k1nkCw=='),
        ),
    ]
