# Generated by Django 3.2.5 on 2021-08-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0006_alter_postulations_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulations',
            name='coupon',
            field=models.TextField(default='CIJPM'),
        ),
    ]
