# Generated by Django 3.2.5 on 2021-08-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0014_alter_postulations_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulations',
            name='coupon',
            field=models.TextField(default='XO7OZ', null=True),
        ),
    ]
