# Generated by Django 3.2.5 on 2021-08-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulations', '0018_alter_postulations_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulations',
            name='coupon',
            field=models.TextField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulations',
            name='phone',
            field=models.TextField(max_length=9),
        ),
    ]
