# Generated by Django 3.2.5 on 2021-08-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
