# Generated by Django 3.2.5 on 2021-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='image',
            field=models.ImageField(default='-', max_length=255, upload_to='benefits'),
        ),
    ]
