# Generated by Django 3.2.5 on 2021-07-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.TextField()),
                ('description', models.TextField()),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modules')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
