# Generated by Django 3.2.5 on 2021-07-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='modules_id',
            new_name='modules',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='schedule_id',
            new_name='schedule',
        ),
    ]
